### ISSUE TITLE
Prepare role for open-sourcing

### ISSUE THREAD

**Issue by paulrbr-fl** [fretlink/ansible-kong-app#24]
### Some important steps before releasing it

- [x] Look for secrets in git history and revoke them if needed.
- [ ] Documentation (notably examples?). See #22 
- [x] Use Kong idempotency instead of custom code. See #23
- [ ] Make it releasable to ansible-galaxy?
- [x] Remove Slack token from `.travis.yml` file (and from git history) #21

**Comment by paulrbr-fl** [comment]
As of today, it's public :tada:
